Repository Marione-Tainara/SAP007-burger-queen-api-client, pull requests merged in 2022-05, with the labels that each got.

#1 Criando Página de Cadastro
  src/App.js
  src/components/Button.js
  src/pages/login.jsx
  src/pages/register.jsx
Labels: good first issue

#2 Feat/add page login
  package-lock.json
  package.json
  src/App.jsx
  src/App.test.jsx
  src/components/Button/index.jsx
  src/components/Button/style.module.css
  src/components/Footer.js
  src/components/Footer/Footer.jsx
  src/components/Footer/Footer.module.css
  src/components/Input/Input.module.css
  src/components/Input/InputEmail.jsx
  src/components/Input/InputPassword.jsx
  src/components/Logo/index.jsx
  src/components/Logo/style.module.css
  src/index.jsx
  src/pages/login.jsx
  src/pages/register.jsx
  src/setupTests.jsx
Labels: good first issue

#4 Co-authored-by: Marione-Tainara <mari.tainara@gmail.com>
  src/App.jsx
  src/components/Button/index.jsx
  src/components/Footer/index.jsx
  src/components/Footer/style.module.css
  src/components/Input/InputEmail.jsx
  src/components/Input/InputPassword.jsx
  src/components/Input/index.jsx
  src/components/Input/style.module.css
  src/index.css
  src/pages/login.jsx
  src/pages/register.jsx
Labels: enhancement

#5 Validação cadastro, implementada rotas adicionais
  src/App.jsx
  src/App.test.jsx
  src/components/Button/style.module.css
  src/components/Footer/index.jsx
  src/components/Footer/style.module.css
  src/components/Input/index.jsx
  src/components/Input/style.module.css
  src/index.css
  src/pages/register.jsx
  src/services/api.jsx
  src/services/error.jsx
  src/services/token.jsx
  src/tests/App.test.jsx
  src/tests/mocks
  src/tests/setupTests.jsx
Labels: bug

#6 Feat/add validator register
  src/App.jsx
  src/components/Button/index.jsx
  src/components/Button/style.module.css
  src/components/Footer/style.module.css
  src/components/Input/index.jsx
  src/components/Input/style.module.css
  src/components/Logo/index.jsx
  src/components/Logo/style.module.css
  src/components/Message/index.jsx
  src/components/Message/style.module.css
  src/index.css
  src/pages/hall.jsx
  src/pages/kitchen.jsx
  src/pages/login.jsx
  src/pages/register.jsx
  src/services/AuthProvider.jsx
  src/services/api.jsx
  src/services/token.jsx
Labels: good first issue

#7 Inicio ajustes responsivo e testes componentes
  src/components/Button/style.module.css
  src/components/Conteiner/index.jsx
  src/components/Conteiner/style.module.css
  src/components/Footer/style.module.css
  src/components/Input/style.module.css
  src/components/Logo/style.module.css
  src/index.css
  src/tests/App.test.jsx
Labels: good first issue

#8 adicionado testes e implementação história 1
  src/App.jsx
  src/components/Button/index.jsx
  src/components/Footer/index.jsx
  src/components/Footer/style.module.css
  src/components/Input/style.module.css
  src/components/Logo/index.jsx
  src/components/Logo/style.module.css
  src/index.css
  src/pages/hall.jsx
  src/pages/kitchen.jsx
  src/pages/login.jsx
  src/pages/register.jsx
  src/services/api.jsx
  src/tests/App.test.jsx
  src/tests/Button.test.jsx
  src/tests/Footer.test.jsx
  src/tests/Input.test.jsx
  src/tests/Login.test.jsx
  src/tests/Logo.test.jsx
  src/tests/Register.test.jsx
  src/tests/mocks
  src/tests/setupTests.jsx
Labels: good first issue

#9 rotas privadas adicionadas
  src/App.jsx
  src/pages/hall.jsx
  src/pages/kitchen.jsx
  src/services/AuthProvider.jsx
  src/services/PrivateRoute.jsx
Labels: good first issue

#10 adiconada função de seleção dos menus
  src/components/Card/index.jsx
  src/components/Card/style.module.css
  src/components/Footer/index.jsx
  src/components/Header/index.jsx
  src/components/Header/style.module.css
  src/components/PurchaseOrder/index.jsx
  src/components/PurchaseOrder/style.module.css
  src/img/finn.jpg
  src/pages/hall.jsx
  src/services/Products.jsx
  src/services/api.jsx
Labels: good first issue

#11 ajuste input radio
  src/components/Input/style.module.css
  src/components/Role/index.jsx
  src/components/Role/style.module.css
  src/index.css
  src/pages/register.jsx
Labels: good first issue

#12 função de adicionar produtos no pedido
  src/App.jsx
  src/components/Card/index.jsx
  src/global/GlobalContext.jsx
  src/global/GlobalState.jsx
Labels: good first issue

#15 mostrando informações do cliente na tela
  src/pages/hall.jsx
Labels: bug

#16 tentando fazer pedidos e ajustando a semântica
  src/App.jsx
  src/components/Button/index.jsx
  src/components/Button/style.module.css
  src/components/Card/index.jsx
  src/components/Footer/index.jsx
  src/components/Footer/style.module.css
  src/components/Header/index.jsx
  src/components/Input/index.jsx
  src/components/Logo/index.jsx
  src/components/Logo/style.module.css
  src/components/Message/index.jsx
  src/components/Message/style.module.css
  src/components/Role/index.jsx
  src/components/TemplateOrder/index.jsx
  src/components/TemplateOrder/style.module.css
  src/global/GlobalContext.jsx
  src/global/GlobalState.jsx
  src/img/finn.jpg
  src/pages/hall.jsx
  src/pages/login.jsx
  src/pages/register.jsx
  src/services/PrivateRoute.jsx
  src/services/api.jsx
  src/services/error.jsx
  src/tests/Button.test.jsx
  src/tests/Footer.test.jsx
  src/tests/Input.test.jsx
  src/tests/Login.test.jsx
  src/tests/Logo.test.jsx
  src/tests/Register.test.jsx
Labels: bug

#18 Feat/add css message
  src/components/Input/index.jsx
  src/components/Message/index.jsx
  src/components/Message/style.module.css
  src/components/Role/index.jsx
  src/components/TemplateOrder/index.jsx
  src/index.css
  src/pages/hall.jsx
  src/pages/kitchen.jsx
  src/pages/login.jsx
  src/pages/register.jsx
  src/services/api.jsx
  src/tests/Input.test.jsx
  src/tests/Login.test.jsx
Labels: good first issue

#19 adicionando itens ao pedido e componente para deletar
  src/components/TemplateOrder/index.jsx
  src/pages/hall.jsx
  src/pages/login.jsx
  src/services/api.jsx
Labels: good first issue

#20 Função deletar e total da compra implementada
  src/components/Button/style.module.css
  src/components/Card/index.jsx
  src/components/Card/style.module.css
  src/components/Input/style.module.css
  src/components/TemplateOrder/index.jsx
  src/components/TemplateOrder/style.module.css
  src/index.css
  src/pages/hall.jsx
Labels: good first issue
